image: alpine

before_script:
  - apk --no-cache add make openssh-client py3-setuptools py3-pip python3-dev py3-pillow py3-lxml
  - pip3 install nikola
  - nikola theme -i bootstrap3

build:
  stage: build
  script:
    - nikola build
    - mv output public
  artifacts:
    paths:
      - public

pages:
  script:
    - nikola build
    - mv output public
  artifacts:
    paths:
      - public
  only:
    - master@openlp/website
